# Generated by Django 2.0.2 on 2018-10-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20181006_1931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name_plural': 'Projects'},
        ),
        migrations.AddField(
            model_name='projects',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
