# Generated by Django 2.0.8 on 2018-10-10 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20181009_0836'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recommendation',
            new_name='Testimonial',
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='recommendation',
            new_name='testimonial',
        ),
    ]
