# Generated by Django 2.0.2 on 2018-10-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header',
            field=models.ImageField(blank=True, null=True, upload_to='headers'),
        ),
    ]
