# Generated by Django 2.0.2 on 2018-10-05 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_pinned'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('pinned', '-publish')},
        ),
    ]
