# Generated by Django 2.0.2 on 2018-10-05 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20181005_0751'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinnedPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='pinned',
        ),
        migrations.AddField(
            model_name='pinnedpost',
            name='pinned_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned', to='blog.Post'),
        ),
    ]
