# Generated by Django 2.0.2 on 2018-10-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20181005_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinnedpost',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
