# Generated by Django 2.0.2 on 2018-10-05 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_pinnedpost_is_pinned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pinnedpost',
            name='pinned_post',
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publish',)},
        ),
        migrations.DeleteModel(
            name='PinnedPost',
        ),
    ]
