# Generated by Django 2.0.2 on 2018-10-07 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20181005_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinnedPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pinned', models.BooleanField(default=False)),
                ('pinned_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned', to='blog.Post')),
            ],
        ),
    ]
