# Generated by Django 2.0.8 on 2018-10-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_pinnedpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pinnedpost',
            name='pinned_post',
        ),
        migrations.AddField(
            model_name='post',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='PinnedPost',
        ),
    ]
