# Generated by Django 2.0.8 on 2018-10-10 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20181009_0834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pinned', '-publish')},
        ),
    ]
